name: Build and Deploy for Go service

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches: [ main ]

env:
  APP_NAME: trace-test
  NAMESPACE: redis-app
  CLUSTER_NAME: sporetm-aks
  resource_group: kops
  AZURE_LOGIN_SERVER: kopsdev26bf3467a7874ff19f0965e516c2918a.azurecr.io

jobs:
  dockerize:
    runs-on: ubuntu-latest
    name: 🐳 Dockerize

    outputs:
      image: ${{ steps.output-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o main

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_LOGIN_SERVER }}
          username: ${{ secrets.SVC_PRI_USERNAME }}
          password: ${{ secrets.SVC_PRI_PASSWORD }}

      - name: Build and Push Docker Image to GCR
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ env.AZURE_LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}

  deployment:
    runs-on: ubuntu-latest
    needs: dockerize
    name: Deploy
    steps:
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.resource_group }}
          cluster-name: ${{env.CLUSTER_NAME }}
          admin: true

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to AKS
        run: kubectl set image deployment/${{ env.APP_NAME }} ${{ env.APP_NAME }}=${{ env.AZURE_LOGIN_SERVER }}${{ env.APP_NAME }}:${{ github.sha }} --namespace  ${{ env.NAMESPACE }}
